spring:
  application:
    name: metric-agent
  config:
    import:
      - classpath:/config/grantmetric.yaml
  profiles:
    active: prd
server:
  port: 8080
logging:
  level:
    org.springdoc: INFO
    io.swagger.v3: INFO
    com.cloudzmp: DEBUG
zcp:
  token: null
  realm: ags
  endpoints:
    k8s:
      - https://kubernetes.default.svc
    nginx:
      - http://private-ingress-nginx-controller-metrics.kube-system.svc:10254
    cert:
      - http://zcp-cert-manager.cert-manager.svc:9042
    tekton:
      - http://tekton-pipelines-controller.cicd.svc:9090
      - http://tekton-pipelines-webhook.cicd.svc:9090
    harbor:
      - http://ags-registry-harbor-core.ags-system.svc:8001
      - http://ags-registry-harbor-exporter.ags-system.svc:8001
      - http://ags-registry-harbor-jobservice.ags-system.svc:8001
      - http://ags-registry-harbor-registry.ags-system.svc:8001
    argocd:
      - http://platform-argocd-application-controller-metrics.argocd.svc:8082
      - http://platform-argocd-server-metrics.argocd.svc:8083
      - http://platform-argocd-repo-server.argocd.svc:8081
      - http://platform-argocd-dex-server.argocd.svc:5558
      - http://platform-argocd-repo-server.argocd.svc:8081
      - http://ags-argocd-application-controller-metrics.ags-system.svc:8082
      - http://ags-argocd-server-metrics.ags-system.svc:8083
      - http://ags-argocd-repo-server.ags-system.svc:8081
      - http://ags-argocd-dex-server.ags-system.svc:5558
      - http://ags-argocd-repo-server.ags-system.svc:8081
    loki:
      - http://loki-read.logging.svc:3100
      - http://loki-write.logging.svc:3100
      - http://loki-backend.logging.svc:3100
